### ISSUE TITLE
.NET 4.5 mscorlib.dll cannot be read.

### ISSUE THREAD

**Issue by tecteun** [HaxeFoundation/hxcs#23]
When trying to compile a .net 4.5 project (depending on Azure web jobs SDK)

adding
*-net-lib C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll*

results in the following error:
*PeReader.Error_message("Error reading compressed data. Invalid first byte: e5")
Build halted with errors (haxe.exe).*

Also see 
https://github.com/HaxeFoundation/haxe/issues/4151#issuecomment-94123495

**Comment by tecteun** [comment]
Still:
 :+1: for some love

**Comment by tecteun** [comment]
because it seems not related to hxcs.

**Comment by waneck** [comment]
Please add an issue on the Haxe tracker. As for using .net 4, you can add `-D net_ver=40`  to the Haxe parameters; Normally it's best to use mono's .dlls as they are much more compliant to the .net specification. Anyway we should look at this problem

**Comment by joel-arthur** [comment]
Same error for me using Mono's .Net 4.5 .dlls:

PeReader.Error_message("Error reading compressed data. Invalid first byte: e5")

**Comment by waneck** [comment]
I don't think @tecteun has added an issue to the Haxe tracker. Please add it, and I'll take a look at it

**Comment by joel-arthur** [comment]
Thanks @waneck. Issue opened.
