### ISSUE TITLE
EReg.matched() doesn't throw exception for non-existing group

### ISSUE THREAD

**Issue by sebthom** [HaxeFoundation/hxcs#26]
The Haxe API documentation at http://api.haxe.org/EReg.html#matched states:

```
If no such sub-group exists, an exception is thrown
```

On C# targets however no exception is thrown, but null is returned.

Example:

``` haxe
class Test {
    static function main() {
        var pattern = ~/test/g;
        pattern.match("test");
        trace(pattern.matched(1));  // prints "null" on C#, but should throw an exception
    }
}
```

**Comment by NemoStein** [comment]
JS doesn't throw, also...
Returning `null` is more suitable (IMO), but the documentation is heavily misleading.

**Comment by sebthom** [comment]
Closing in favor of https://github.com/HaxeFoundation/haxe/issues/5352
