### ISSUE TITLE
static fields initialization

### ISSUE THREAD

**Issue by Yoshimitsu77** [HaxeFoundation/hxcs#29]
hxcs v3.2.0
haxe v3.4.0

`static var b:Array<Int> = a.concat([1]);`
`static var a:Array<Int> = [1];`

this code will compile successfuly, and work fine targeting js or as3, but not c#.
this initialization of 'a' and 'b' arrays will be moved into constructor, and left in presentet sequence:
first, b = a.concat(), then, a = [].

`static var a:Array<Int> = [1];`
`static var b:Array<Int> = a.concat([1]);`

in this case it will work. 

This issue will trigger no wornings of errors, exept 'null referense exception' during C# runtime.

**Comment by Simn** [comment]
Haxe preserves field order, so this is working as intended.

**Comment by Yoshimitsu77** [comment]
yes it is, and in this casr it IS a problem...
haxe code is not senicitive to fields order. compiler will an error 'usong undefined local variable' in case of putting same code inside a single function. But it is fine in case of class fields. No errors. no wornings, it's just working for some targetst, and do not working for С#

**Comment by Simn** [comment]
This doesn't work on JS either, it's your responsibility to get your statics in the correct order.
