### ISSUE TITLE
interfaces

### ISSUE THREAD

**Issue by Yoshimitsu77** [HaxeFoundation/hxcs#30]
C# interfaces can not contain variables: only methods.
There is no any warnings of errors: hxcs just ignores all of it, and all of it's uages. There is no warnings of error messages

**Comment by nadako** [comment]
Please note that `hxcs` is just a tool called by haxe to discover and invoke C# compiler on haxe-generated c# code, so issues like this should go to the [haxe repository](https://github.com/haxefoundation/haxe/issues).

Anyway, I don't understand what errors or warnings are you expecting? It's true that C# interfaces doesn't support variables, so they are not present in the generated interface. For accessing variables through interface, Haxe generates a reflection call. This is arguably not very good performance-wise, but it's still correct. If you have any suggestions regarding that - please open a new issue on Haxe repository.

**Comment by nadako** [comment]
@Simn @waneck could you close this please?

**Comment by Simn** [comment]
You've got the power!

**Comment by Yoshimitsu77** [comment]
@nadako 
`public var myInterface:IMyInterface;`
`<...>`
`myInterface.myVariable = 1; //whole this line will just disappear. No reflections. nothing.`

**Comment by nadako** [comment]
that's not true:

```haxe
interface IMyInterface {
    var myVariable:Int;
}

class Main {
    static var myInterface:IMyInterface;

    static function main() {
        myInterface.myVariable = 1;
    }
}
```

generated c#:

```cs
public static void main() {
	unchecked {
		global::haxe.lang.Runtime.setField_f(global::Main.myInterface, "myVariable", 1452177864, ((double) (1) ));
	}
}
```

so we're gonna need a reproducible example
